### ISSUE TITLE
Hi Nacho

### ISSUE THREAD

**Issue by chrisgillison** [nachocinalli/adapt-notifyLinks#1]
Hi Nacho. This extension looks really great and I'd love to use it - but I'm confused!
I have a simple text component in my course with a notify link. I want to launch a graphic component from that link. So I added the enabler to the course.json, but what happens in the components.json isn't clear to me.

Firstly, in the example. json it says to put the following in components.json, but I''m not sure where:
```
"_notifyLinks": {
      "_name": "component-unique-name"
}
```
Secondly, where does the graphic component which is launched by the notify link sit/exist? I put it in my components.json with a _parentID of the notify links text component. Didn't work.

Please help!

**Comment by nachocinalli** [comment]
Hi Chris, it should look something like this:
```
[
    {
        "_id": "c-05",
        "_component": "text",
        "body": "<a class=\"notify-link\" href=\"#c-10\">Open graphic c-10</a>"
    },
    {
        "_id": "c-10",
        "_component": "graphic"
    }
]
```

You need to create an anchor tag and put the id of the graphic in the href.

**Comment by nachocinalli** [comment]
Sorry, I forgot that the last update of this extension added the possibility to make the reference with a custom name.
Could you try this way?
```

[
    {
        "_id": "c-05",
        "_component": "text",
        "body": "<a class=\"notify-link\" href=\"graphic-001\">Open graphic c-10</a>"
    },
    {
        "_id": "c-10",
        "_component": "graphic",
        "_notifyLinks": {
            "_name": "graphic-001"
        }
    }
]
```

**Comment by chrisgillison** [comment]
Hi Nacho,

Many thanks for getting back so quickly. I now have something - please see the screenshots - my link opens graphic-001 in a notify popup. 

So my question is, how do I **_hide_** graphic-001 before clicking the link? Currently it's just sitting in the components.json so is already displayed (not ideal!!)

![ss1](https://github.com/nachocinalli/adapt-notifyLinks/assets/17124184/afba116e-5997-4e6c-b3e2-603b321a1afd)
![ss2](https://github.com/nachocinalli/adapt-notifyLinks/assets/17124184/3e3c296b-3262-48aa-a31d-6be063d9fd65)

**Comment by nachocinalli** [comment]
You can use a hidden block, or you can structure the course by having a separate page with the components you want to open with notify links. I prepared an example for [option 1](https://adaptlearning-no-core.web.app/starters/notify-links-1.zip) and for [option 2](https://adaptlearning-no-core.web.app/starters/notify-links-2.zip).

**Comment by chrisgillison** [comment]
Oh wow. Many thanks Ignacio! I got it working and I LOVE it!!

My problem was that I was blissfully unaware of the option to hide a block!

Great work.
